import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

export type StmtTab = 'generate' | 'downloads' | 'scheduled' | 'certificates';
export type ModalKey =
  | 'emailStatement' | 'previewStatement' | 'scheduleAutoGen'
  | 'stmtDetail' | 'certModal' | 'newSchedule' | 'editSchedule'
  | 'deleteSchedule' | 'pauseSchedule' | 'requestCert'
  | 'downloadComplete' | 'shareStatement' | 'statOptions';

export interface DownloadItem {
  icon: string;
  iconCls: string;
  name: string;
  period: string;
  date: string;
  size: string;
}

export interface Schedule {
  icon: string;
  iconCls: string;
  name: string;
  desc: string;
  active: boolean;
}

export interface Certificate {
  icon: string;
  iconCls: string;
  name: string;
  desc: string;
  available: boolean;
}

@Component({
  selector: 'app-statements',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl:'./statements.html',
  styleUrls: ['./statements.scss'],
})
export class StatementsComponent {
  activeTab: StmtTab = 'generate';
  activeModal: ModalKey | null = null;
  selectedDownload: DownloadItem | null = null;
  selectedCert: Certificate | null = null;
  selectedSchedule: Schedule | null = null;

  /* ── stat strip ── */
  stats = [
    { label: 'Generate New', value: 'Now', sub: 'Custom statement', tab: 'generate' as StmtTab },
    { label: 'Recent Downloads', value: '8', sub: 'Last 30 days', tab: 'downloads' as StmtTab },
    { label: 'Auto Statements', value: '2', sub: 'Active schedules', tab: 'scheduled' as StmtTab },
    { label: 'Certificates', value: '5', sub: 'Loan, Tax, Audit', tab: 'certificates' as StmtTab },
  ];

  /* ── generate form ── */
  stmtType = 'all';
  stmtTypes = [
    { key: 'all', label: 'All Accounts', sub: 'Combined statement' },
    { key: 'savings', label: 'Savings Account', sub: 'Deposits & balance' },
    { key: 'shares', label: 'Share Capital', sub: 'Holdings & dividends' },
    { key: 'loans', label: 'Loans', sub: 'Repayments & balances' },
    { key: 'wallet', label: 'Wallet', sub: 'SACCOPay activity' },
    { key: 'mini', label: 'Mini Statement', sub: 'Last 10 transactions' },
  ];
  quickRange = 'Last 30 Days';
  quickRanges = ['Last 7 Days', 'Last 30 Days', 'Last 3 Months', 'Last 6 Months', 'Year to Date', 'Last Year', 'All Time'];
  fromDate = '2024-11-18';
  toDate = '2024-12-18';
  format = 'pdf';
  options = {
    header: true, summary: true, stamp: true,
    balance: true, charts: false, password: false,
  };

  /* ── email form ── */
  emailForm = {
    to: 'john.k@email.com', cc: '', subject: 'My SACCO Statement — Nov 18 – Dec 18, 2024',
    message: '', protect: false,
  };

  /* ── schedule form ── */
  scheduleForm = {
    name: '', type: 'all', frequency: 'Monthly', day: '1st',
    format: 'pdf', email: 'john.k@email.com',
  };

  /* ── downloads ── */
  downloads: DownloadItem[] = [
    { icon: '📕', iconCls: 'pdf', name: 'Combined Statement — All Accounts', period: 'Period: Nov 18 – Dec 18, 2024 · Generated by you', date: 'Today, 2:30 PM', size: '1.2 MB' },
    { icon: '📗', iconCls: 'excel', name: 'Savings Account Statement — Q4 2024', period: 'Period: Oct 1 – Dec 17, 2024', date: 'Yesterday, 4:20 PM', size: '845 KB' },
    { icon: '📕', iconCls: 'pdf', name: 'Loan Statement — LN-2024-00845', period: 'Education Loan · Full repayment history', date: 'Dec 16, 2024', size: '620 KB' },
    { icon: '📘', iconCls: 'csv', name: 'Wallet Statement — November 2024', period: 'SACCOPay Wallet activity', date: 'Dec 12, 2024', size: '215 KB' },
    { icon: '📕', iconCls: 'pdf', name: 'Share Capital Statement — 2024 Annual', period: 'Holdings, dividends & contributions', date: 'Dec 5, 2024', size: '480 KB' },
  ];
  downloadFilter = '';

  /* ── schedules ── */
  schedules: Schedule[] = [
    { icon: '📅', iconCls: 'red', name: 'Monthly Combined Statement', desc: '1st of every month · PDF · Sent to john.k@email.com', active: true },
    { icon: '📊', iconCls: 'green', name: 'Quarterly Loan Statement', desc: 'Last day of each quarter · Excel · Sent to john.k@email.com', active: true },
  ];

  /* ── certificates ── */
  certificates: Certificate[] = [
    { icon: '🛡', iconCls: 'blue', name: 'Loan Clearance Certificate', desc: 'For LN-2024-00750 · Personal Loan · Cleared Mar 2024', available: true },
    { icon: '📋', iconCls: 'blue', name: 'Tax Withholding Certificate (WHT)', desc: 'FY 2024 · For KRA filing · Dividend tax withheld', available: true },
    { icon: '🛡', iconCls: 'blue', name: 'Share Capital Certificate', desc: '45 shares · Total value: KES 45,000 · Issued Dec 2024', available: true },
    { icon: '📇', iconCls: 'purple', name: 'Membership Certificate', desc: 'Member since Jan 2022 · Active status', available: true },
    { icon: '📄', iconCls: 'amber', name: 'Audit Confirmation Letter', desc: 'Balance & holdings as at Dec 18, 2024 · For auditors', available: false },
  ];

  /* ── toast ── */
  toast: { message: string; type: 'success' | 'info' } | null = null;
  private toastTimer: any;

  /* ── modal helpers ── */
  openModal(key: ModalKey): void {
    this.activeModal = key;
    document.body.style.overflow = 'hidden';
  }
  closeModal(): void {
    this.activeModal = null;
    document.body.style.overflow = '';
  }
  openDownload(d: DownloadItem): void { this.selectedDownload = d; this.openModal('stmtDetail'); }
  openCert(c: Certificate): void { this.selectedCert = c; this.openModal(c.available ? 'certModal' : 'requestCert'); }
  openEditSchedule(s: Schedule): void { this.selectedSchedule = s; this.openModal('editSchedule'); }
  openDeleteSchedule(s: Schedule): void { this.selectedSchedule = s; this.openModal('deleteSchedule'); }
  toggleSchedule(s: Schedule): void { s.active = !s.active; }

  /* ── action handlers ── */
  previewStatement(): void { this.openModal('previewStatement'); }
  generateDownload(): void { this.closeModal(); this.showToast('Statement generated. Check Recent Downloads.', 'success'); }
  sendEmail(): void { this.closeModal(); this.showToast('Statement emailed to ' + this.emailForm.to, 'success'); }
  saveSchedule(): void { this.closeModal(); this.showToast('Auto-statement schedule saved.', 'success'); }
  deleteScheduleConfirm(): void { this.closeModal(); this.showToast('Schedule removed.', 'info'); }
  downloadCert(): void { this.showToast('Certificate downloaded.', 'success'); }
  requestCertSubmit(): void { this.closeModal(); this.showToast('Certificate request submitted.', 'info'); }
  downloadItem(): void { this.showToast('File downloaded.', 'success'); }
  shareItem(): void { this.openModal('shareStatement'); }
  sendItemEmail(): void { this.openModal('emailStatement'); }

  showToast(message: string, type: 'success' | 'info' = 'success'): void {
    this.toast = { message, type };
    clearTimeout(this.toastTimer);
    this.toastTimer = setTimeout(() => (this.toast = null), 3200);
  }
  dismissToast(): void { this.toast = null; }

  setQuickRange(r: string): void {
    this.quickRange = r;
    const now = new Date();
    const to = now.toISOString().split('T')[0];
    const from = new Date(now);
    const daysMap: Record<string, number> = {
      'Last 7 Days': 7, 'Last 30 Days': 30,
      'Last 3 Months': 90, 'Last 6 Months': 180, 'Last Year': 365,
    };
    from.setDate(from.getDate() - (daysMap[r] ?? 30));
    this.fromDate = from.toISOString().split('T')[0];
    this.toDate = to;
  }

  get filteredDownloads(): DownloadItem[] {
    if (!this.downloadFilter) return this.downloads;
    return this.downloads.filter(d => d.iconCls === this.downloadFilter);
  }
}
