import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

/* ─── Interfaces ─── */
interface StatementItem {
  name: string;
  description: string;
  format: string;
  size: string;
  date: string;
  period?: string;
  fileName?: string;
}

interface ScheduleItem {
  id: number;
  name: string;
  description: string;
  format: string;
  frequency: string;
  status: string;
}

interface CertificateItem {
  name: string;
  description: string;
  status: string;
  icon: string;
  iconBg: string;
  iconColor: string;
  fileName?: string;
}

interface PreviewTransaction {
  date: string;
  description: string;
  debit: string;
  credit: string;
  balance: string;
}

/* ─── Component ─── */
@Component({
  selector: 'app-statements',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './statements.html',
  styleUrls: ['./statements.scss']
})
export class StatementsComponent {

  /* ═══════════ TAB STATE ═══════════ */
  activeTab: string = 'generate';

  /* ═══════════ GENERATE TAB ═══════════ */
  selectedStmtType: string = 'all';
  quickRange: string = '30d';
  dateFrom: string = '2024-11-18';
  dateTo: string = '2024-12-18';
  selectedFormat: string = 'pdf';

  /* Options checkboxes */
  optHeader: boolean = true;
  optBalance: boolean = true;
  optSummary: boolean = true;
  optCharts: boolean = false;
  optStamp: boolean = true;
  optPwd: boolean = false;

  /* ═══════════ DOWNLOADS TAB ═══════════ */
  recentDownloads: StatementItem[] = [
    {
      name: 'Combined Statement — All Accounts',
      description: 'Period: Nov 18 – Dec 18, 2024 · Generated by you',
      format: 'PDF',
      size: '1.2 MB',
      date: 'Today, 2:30 PM',
      period: 'Nov 18 – Dec 18, 2024',
      fileName: 'Combined-Statement.pdf'
    },
    {
      name: 'Savings Account Statement — Q4 2024',
      description: 'Period: Oct 1 – Dec 17, 2024',
      format: 'Excel',
      size: '845 KB',
      date: 'Yesterday, 4:20 PM',
      period: 'Q4 2024',
      fileName: 'Savings-Q4.xlsx'
    },
    {
      name: 'Loan Statement — LN-2024-00845',
      description: 'Education Loan · Full repayment history',
      format: 'PDF',
      size: '620 KB',
      date: 'Dec 16, 2024',
      period: 'LN-2024-00845',
      fileName: 'Loan-Statement.pdf'
    },
    {
      name: 'Wallet Statement — November 2024',
      description: 'SACCOPay Wallet activity',
      format: 'CSV',
      size: '215 KB',
      date: 'Dec 12, 2024',
      period: 'Nov 2024',
      fileName: 'Wallet-Nov.csv'
    },
    {
      name: 'Share Capital Statement — 2024 Annual',
      description: 'Holdings, dividends & contributions',
      format: 'PDF',
      size: '480 KB',
      date: 'Dec 5, 2024',
      period: '2024 Annual',
      fileName: 'Share-Annual.pdf'
    }
  ];

  selectedStmt: StatementItem | null = null;

  /* ═══════════ SCHEDULED TAB ═══════════ */
  schedules: ScheduleItem[] = [
    {
      id: 1,
      name: 'Monthly Combined Statement',
      description: '1st of every month · PDF · Sent to john.k@email.com',
      format: 'PDF',
      frequency: 'Monthly',
      status: 'Active'
    },
    {
      id: 2,
      name: 'Quarterly Loan Statement',
      description: 'Last day of each quarter · Excel · Sent to john.k@email.com',
      format: 'Excel',
      frequency: 'Quarterly',
      status: 'Active'
    }
  ];

  /* ═══════════ CERTIFICATES TAB ═══════════ */
  certificates: CertificateItem[] = [
    {
      name: 'Loan Clearance Certificate',
      description: 'For LN-2024-00750 · Personal Loan · Cleared Mar 2024',
      status: 'Available',
      icon: 'patch-check-fill',
      iconBg: 'rgba(0,208,132,0.1)',
      iconColor: 'var(--primary)',
      fileName: 'Loan-Clearance.pdf'
    },
    {
      name: 'Tax Withholding Certificate (WHT)',
      description: 'FY 2024 · For KRA filing · Dividend tax withheld',
      status: 'Available',
      icon: 'receipt-cutoff',
      iconBg: 'rgba(33,150,243,0.1)',
      iconColor: 'var(--blue)',
      fileName: 'WHT-Certificate.pdf'
    },
    {
      name: 'Share Capital Certificate',
      description: '45 shares · Total value: KES 45,000 · Issued Dec 2024',
      status: 'Available',
      icon: 'shield-fill-check',
      iconBg: 'rgba(26,35,126,0.1)',
      iconColor: '#1a237e',
      fileName: 'Share-Certificate.pdf'
    },
    {
      name: 'Membership Certificate',
      description: 'Member since Jan 2022 · Active status',
      status: 'Available',
      icon: 'person-badge',
      iconBg: 'rgba(156,39,176,0.1)',
      iconColor: 'var(--purple)',
      fileName: 'Membership-Certificate.pdf'
    },
    {
      name: 'Audit Confirmation Letter',
      description: 'Balance & holdings as at Dec 18, 2024 · For auditors',
      status: 'Request Required',
      icon: 'file-earmark-check',
      iconBg: 'rgba(255,152,0,0.1)',
      iconColor: 'var(--orange)'
    }
  ];

  /* ═══════════ PREVIEW DATA ═══════════ */
  previewTransactions: PreviewTransaction[] = [
    { date: 'Nov 18', description: 'Opening Balance', debit: '', credit: '', balance: '95,000' },
    { date: 'Nov 25', description: 'Salary Deposit', debit: '', credit: '85,000', balance: '180,000' },
    { date: 'Nov 28', description: 'Loan Repayment', debit: '15,000', credit: '', balance: '165,000' },
    { date: 'Dec 1', description: 'Share Purchase', debit: '10,000', credit: '', balance: '155,000' },
    { date: 'Dec 5', description: 'Withdrawal — M-Pesa', debit: '30,000', credit: '', balance: '125,000' },
    { date: 'Dec 10', description: 'Wallet Top-up', debit: '', credit: '5,000', balance: '130,000' },
    { date: 'Dec 17', description: 'Transfer to Savings', debit: '1,550', credit: '', balance: '128,450' }
  ];

  /* ═══════════ MODAL STATES ═══════════ */
  showPreviewModal: boolean = false;
  showDeliveryModal: boolean = false;
  showScheduleModal: boolean = false;
  showEditScheduleModal: boolean = false;
  showStmtDetailModal: boolean = false;
  showCertificateModal: boolean = false;
  showCertRequestModal: boolean = false;
  showProfileModal: boolean = false;

  /* ═══════════ DELIVERY MODAL FIELDS ═══════════ */
  deliveryEmail: string = 'john.k@email.com';
  deliveryCc: string = '';
  deliverySubject: string = 'My SACCO Statement — Nov 18 – Dec 18, 2024';
  deliveryMessage: string = '';
  deliveryPwd: boolean = false;

  /* ═══════════ SCHEDULE MODAL FIELDS ═══════════ */
  scheduleType: string = 'Combined (All Accounts)';
  scheduleFrequency: string = 'Monthly';
  scheduleDay: string = '1st of month';
  scheduleFormat: string = 'PDF';
  scheduleDelivery: string = 'Email';
  scheduleEmail: string = 'john.k@email.com';

  /* ═══════════ EDIT SCHEDULE FIELDS ═══════════ */
  editFrequency: string = 'Monthly';
  editDay: string = '1st of month';
  editEmail: string = 'john.k@email.com';

  /* ═══════════ CERTIFICATE MODAL FIELDS ═══════════ */
  certModalTitle: string = 'Certificate';
  certModalDesc: string = 'Certificate description';

  /* ═══════════ CERT REQUEST FIELDS ═══════════ */
  certRequestName: string = '';
  certRequestEmail: string = '';
  certRequestReason: string = '';

  /* ═══════════ TOAST ═══════════ */
  toastVisible: boolean = false;
  toastMessage: string = '';
  private toastTimeout: ReturnType<typeof setTimeout> | null = null;

  /* ════════════════════════════════════════════════
     TAB SWITCHING
     ════════════════════════════════════════════════ */
  switchTab(tab: string): void {
    this.activeTab = tab;
  }

  /* ════════════════════════════════════════════════
     GENERATE TAB METHODS
     ════════════════════════════════════════════════ */
  selectStmtType(type: string): void {
    this.selectedStmtType = type;
  }

  selectFormat(format: string): void {
    this.selectedFormat = format;
  }

  setQuickRange(range: string): void {
    this.quickRange = range;
    const today = new Date();
    const from = new Date();

    switch (range) {
      case '7d':
        from.setDate(today.getDate() - 7);
        break;
      case '30d':
        from.setDate(today.getDate() - 30);
        break;
      case '3m':
        from.setMonth(today.getMonth() - 3);
        break;
      case '6m':
        from.setMonth(today.getMonth() - 6);
        break;
      case 'ytd':
        from.setMonth(0, 1);
        break;
      case 'lyr':
        from.setFullYear(today.getFullYear() - 1, 0, 1);
        today.setFullYear(today.getFullYear() - 1, 11, 31);
        break;
      case 'all':
        from.setFullYear(2020, 0, 1);
        break;
    }

    this.dateFrom = from.toISOString().split('T')[0];
    this.dateTo = today.toISOString().split('T')[0];
  }

  generateAndDownload(): void {
    this.closeModal('previewModal');
    this.showToast('Statement generated and downloading... 📄');
  }

  /* ════════════════════════════════════════════════
     DOWNLOADS TAB METHODS
     ════════════════════════════════════════════════ */
  openStmtDetail(stmt: StatementItem): void {
    this.selectedStmt = stmt;
    this.openModal('stmtDetailModal');
  }

  downloadStmt(name: string): void {
    this.showToast(`Downloading ${name}...`);
  }

  emailStmt(name: string): void {
    this.closeModal('stmtDetailModal');
    setTimeout(() => this.openModal('deliveryModal'), 300);
  }

  shareStmt(name: string): void {
    this.showToast(`Sharing ${name}...`);
  }

  deleteStmt(name: string): void {
    if (confirm(`Delete ${name}?`)) {
      this.showToast(`${name} deleted`);
    }
  }

  sendEmail(): void {
    this.closeModal('deliveryModal');
    this.showToast('Statement emailed successfully! 📧');
  }

  /* ════════════════════════════════════════════════
     SCHEDULED TAB METHODS
     ════════════════════════════════════════════════ */
  createSchedule(): void {
    this.closeModal('scheduleModal');
    this.showToast('Auto-statement schedule created! 📅');
  }

  updateSchedule(): void {
    this.closeModal('editScheduleModal');
    this.showToast('Schedule updated!');
  }

  toggleSchedule(sched: ScheduleItem): void {
    sched.status = sched.status === 'Active' ? 'Paused' : 'Active';
    this.showToast(sched.status === 'Paused' ? 'Schedule paused' : 'Schedule resumed');
  }

  deleteSchedule(sched: ScheduleItem): void {
    if (confirm('Delete this schedule?')) {
      this.schedules = this.schedules.filter(s => s.id !== sched.id);
      this.showToast('Schedule deleted');
    }
  }

  /* ════════════════════════════════════════════════
     CERTIFICATES TAB METHODS
     ════════════════════════════════════════════════ */
  openCertModal(cert: CertificateItem): void {
    this.certModalTitle = cert.name;
    this.certModalDesc = cert.description;
    this.openModal('certificateModal');
  }

  submitCertRequest(): void {
    this.closeModal('certRequestModal');
    this.showToast('Certificate request submitted! Admin will process in 1-3 days. 📩');
  }

  /* ════════════════════════════════════════════════
     MODAL MANAGEMENT
     ════════════════════════════════════════════════ */
  openModal(id: string): void {
    switch (id) {
      case 'previewModal': this.showPreviewModal = true; break;
      case 'deliveryModal': this.showDeliveryModal = true; break;
      case 'scheduleModal': this.showScheduleModal = true; break;
      case 'editScheduleModal': this.showEditScheduleModal = true; break;
      case 'stmtDetailModal': this.showStmtDetailModal = true; break;
      case 'certificateModal': this.showCertificateModal = true; break;
      case 'certRequestModal': this.showCertRequestModal = true; break;
      case 'profileModal': this.showProfileModal = true; break;
    }
  }

  closeModal(id: string): void {
    switch (id) {
      case 'previewModal': this.showPreviewModal = false; break;
      case 'deliveryModal': this.showDeliveryModal = false; break;
      case 'scheduleModal': this.showScheduleModal = false; break;
      case 'editScheduleModal': this.showEditScheduleModal = false; break;
      case 'stmtDetailModal': this.showStmtDetailModal = false; break;
      case 'certificateModal': this.showCertificateModal = false; break;
      case 'certRequestModal': this.showCertRequestModal = false; break;
      case 'profileModal': this.showProfileModal = false; break;
    }
  }

  /* ════════════════════════════════════════════════
     TOAST NOTIFICATION
     ════════════════════════════════════════════════ */
  showToast(message: string): void {
    this.toastMessage = message;
    this.toastVisible = true;

    if (this.toastTimeout) {
      clearTimeout(this.toastTimeout);
    }

    this.toastTimeout = setTimeout(() => {
      this.toastVisible = false;
    }, 3500);
  }
}